### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by Jyuart** [Jyuart/homepage#7]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by nathanmorgandrake** [comment]
EXPERIENCE
1989 Ran off from the orphanage and took surname Drake, believing that he and his brother are the heirs of the famous pirate and explorer Sir Francis Drake
1990 Stole the ring which once belonged to Francis Drake. Got acquainted with his best friend Victor "Sully" Sullivan.
October 2003 Stole the golden staff of Ayar Manco from drug lord Ramón Valdez and saved Alex Munoz.
June 2006 Was trying to track down the Eye of Indra artifact.
September 2006 Found the fabled El Dorado and discovered that it's not an ancient city, but rather a cursed golden sarcophagus.
August 2008 Got into jail trying to steal an ancient lamp said to contain clues to the location of Marco Polo's Lost Fleet.
November 2008 Found an ancient city Shambhala
January 2011 Found Atlantis of the Sands, lost city in Rub' al Khali desert.
2014 Found the city of Liberthalia
